name = input("Enter your name: ")
city = input("Enter your City name: ")
print("Hello", name)
print("You live in", city)
name = input("Enter your name:")
age = input("Enter your age:")
favorite_food = input("Enter your favourite dish:")
print("Good Day", name)
print("you are", age,"years old")
print("your favourite food is", favorite_food)